lidar:
  total_ray: 72000
  points_per_arch: 450
  num_channel: 28
  num_segments: 10
  rate: 10
  min_angle_horizontal: -1.0472
  max_angle_horizontal: 1.0472
  angular_uncertainty: 0.000
  lidar_x: 0.5
  lidar_y: 0.0
  lidar_z: 0.5
  perception_sensor_name: "livox_front"
