vehicle_model:
  simple_bicycle_model:
  # some made up values
    kinematics:
      lr: 0.84
      lf: 0.69
      sf: 1.15
      sr: 1.15
    tire:
      Blat: 10
      Clat: -1.39
      Dlat: 1.6
      Elat: 1.0
    aero:
      cla: 4.2
      cda: 1.368
      aeroArea: 1
    m: 230.0
    Izz: 150.0
    wheelRadius: 0.254
    gearRatio: 3
    innerSteeringRatio: 0.255625
    outerSteeringRatio: 0.20375
    nominalVoltageTS: 600.0
    powerGroundForce: 700.0
    powertrainEfficiency: 0.95
